### ISSUE TITLE
Add travis CI setup

### ISSUE THREAD

**Issue by viktigpetterr** [debricked/maven-templates#1]
## Tasks
- [ ] Enable CI via Travis
- [ ] Create travis/debricked CI template 
Here is a start:
```yml
jobs:
  include:
    - stage: Debricked scan
      services:
        - docker
      language: java
      jdk:
        - oraclejdk
      cache:
        directories:
          - $HOME/.m2
      script:
        - mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
        - docker build -t debricked/debricked-scan .
        - docker run --entrypoint "/travis.sh" debricked/debricked-scan

```
